version: "2.1"
orbs:
  gradle: circleci/gradle@3.0.0
jobs:
  make-gradle-executable:
    executor:
      name: gradle/default
      tag: "21.0"
    steps:
      - checkout
      - run: chmod +x nats-reactor-consumer/gradlew
      - gradle/with_cache:
          steps:
            - run:
                command: ./gradlew test
                name: Run Tests
                working_directory: nats-reactor-consumer
      - gradle/collect_test_results:
          reports_path: nats-reactor-consumer/nats-reactive-consumer/build/reports
          test_results_path: nats-reactor-consumer/nats-reactive-consumer/build/test-results
workflows:
  checkout-build-test:
    jobs:
      - make-gradle-executable
