version: "2.1"
orbs:
  gradle: circleci/gradle@3.0.0
jobs:
  make-gradle-executable:
    executor: gradle/default
    steps:
      - checkout
      - run: chmod +x nats-reactor-consumer/gradlew
      - gralde/with_cache:
          steps:
            - run:
                command: ./gradlew test
                name: Run Tests
                working_directory: nats-reactor-consumer
workflows:
  checkout-build-test:
    jobs:
      - make-gradle-executable
